config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'dashboards/index'

  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'dashboards#index'

  resources :admins, :users, :dashboards, :categories, :addresses
  resources :order_details, :wish_lists, :payment_gateways, :coupons, :payments
  resources :abouts, only: [:index]

    resources :cart_items do
      member do
        post 'add_product'
      end
      collection do
        get 'clear_cart'
      end
    end

    resources :user_orders do
      collection do
        get 'confirm_order'
        get 'add_order_address'
        get 'apply_discount'
      end
    end

    resources :products do
      collection do
        get 'search_product'
      end
    end

end

app/models/user_order.rb
class UserOrder < ActiveRecord::Base
  belongs_to :billing_address, class_name: 'Address', foreign_key: 'billing_address_id'
  belongs_to :shipping_address, class_name: 'Address', foreign_key: 'shipping_address_id'
  has_many :order_details, dependent: :destroy
  has_one :payment_gateway
  belongs_to :user
  belongs_to :coupon
end

app/controllers/user_orders_controller.rb
class UserOrdersController < ApplicationController

  before_action :set_cart_items, only: [:index, :show, :confirm_order]
  before_action :set_user_order, only: [:add_order_address, :apply_discount]
  before_action :set_discount, only: [:show]
  before_action :create_user_order, only: [:confirm_order]

  def index
    @user_orders = current_user.user_orders.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user_order = UserOrder.find(params[:id])
    @addresses = current_user.addresses
  end

  def confirm_order
    if @user_order.save
      # NotificationMailer.order_status_email(user_order, current_user).deliver_now
      redirect_to user_order_path(@user_order)
    else
      flash[:alert] = "Something went wrong, Try again!"
      redirect_to cart_items_path
    end
  end

  def add_order_address
    if @user_order.update(billing_address_id: params[:address].to_i, shipping_address_id: params[:address].to_i)
      flash[:notice] = "Address added successfully!"
    else
      flash[:alert] = "Something went wrong, Try again!"
    end
    redirect_to user_order_path(@user_order)
  end

  def apply_discount
    if @user_order.update(coupon_id: params[:coupon_id].to_i)
      flash[:notice] = "Coupon Applied Successfully!"
    else
      flash[:alert] = "Something went wrong, Try again!"
    end
    redirect_to user_order_path(@user_order)
  end

  private
    def create_user_order
      order_details = []
      @user_order = current_user.user_orders.build(total_amount: @total_amount)
      @cart_products.each do |cart_product|
        order_details << @user_order.order_details.build(product_id: cart_product.id, quantity:cart_product.quantity, amount: cart_product.amount)
      end
      @user_order.order_details = order_details
    end
    
    def set_user_order
      @user_order = UserOrder.find(params[:order_id])
    end

    def set_discount
      user_order = UserOrder.find(params[:id])
      if user_order.coupon.present?
        @discount = (user_order.coupon.discount_of/100).to_f
      else
        @discount = 0.0
      end
    end
  
end

app/helpers/user_orders_helper.rb
module UserOrdersHelper
end

app/views/user_orders/index.html.haml
.row
  .col-sm-12
    .col-sm-9
      - if @user_orders.present?
        .table-responsive
          %table.table.table-bordered
            %thead
              %tr
                %td.text-center Product Id
                %td.text-center Order Date
                %td.text-center Amount
                %td.text-center Status
                %td.text-center Action
            - @user_orders.each do |order|
              %tbody
                %tr
                  %td.text-center 
                    = order.id
                  %td.text-center
                    = order.created_at.to_date.strftime('%d-%m-%Y')
                  %td.text-center
                    = order.total_amount
                  %td.text-center
                    = order.status
                  %td.text-center
                    = link_to 'show', order_details_path(order_id: order.id)
    %column#column-right.col-sm-3.hidden-xs
      .list-group
        %a.list-group-item{:input => "#"} Register
        %a.list-group-item{:input => "#"} Forgotten Password
        %a.list-group-item{:input => "#"} My Account
        = link_to 'Address Book', addresses_path, class: 'list-group-item'
        %a.list-group-item{:input => "#"} Wish List
        %a.list-group-item{:input => "#"} Order History
        %a.list-group-item{:input => "#"} Returns
.row
  .col-sm-6.text-left
  .col-sm-6.text-right
    = will_paginate @user_orders

app/views/user_orders/show.html.haml
.row
  = render 'addresses/addresses'
%hr
.row
  .col-sm-1
  .col-sm-9#content
    %h1 Order Summary
    .table-responsive
      %table.table.table-bordered
        %thead
          %tr
            %td.text-center Product Name
            %td.text-center Quantity
            %td.text-center Total
        %tbody
          -@cart_products.each do |product|
            %tr
              %td.text-left
                = link_to product.name, product_path(product)
              %td.text-center
                = product.quantity
              %td.text-right
                = product.amount
          %tr
            %td{colspan: "2"}
              %strong Sub-Total:
            %td.text-right
              %strong
                = @total_amount
            %tr
              %td{colspan: "2"}
                %strong Discount:
              %td.text-right
                %strong.discount
                  = (@total_amount * @discount).ceil
            %tr
              %td{colspan: "2"}
                %strong Total:
              %td.text-right
                %strong.total
                  = @total_amount - (@total_amount * @discount).ceil
    %h3 Get Discount if you have a discount coupon.
    .panel-group#acordion
      .panel.panel-default
        .panel-heading
          %h4.panel-title
            %a.accordion-toggle.collapsed{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapse-coupon"}
              Use Coupon Code
              %i.fa.fa-caret-down
        .panel-collapse.collapse#collapse-coupon
          .panel-body
            = form_tag(apply_discount_user_orders_path, method: :get) do
              .input-group
                = select_tag 'coupon_id', options_for_select(coupons_list), include_blank: 'Select a Coupon here...', class:'form-control', id: 'input-coupon'
                = hidden_field_tag "order_id", params[:id]
                %span.input-group-btn
                  = submit_tag "Apply Coupon", class: 'btn btn-primary', id: 'button-coupon'
    .buttons
      .pull-left
        = link_to 'Continue Shopping', '/', type: 'button', class: 'btn btn-default'
      .pull-right
        = link_to 'Payment', new_payment_gateway_path(:user_order_id=>params[:id]), type: 'button', class: 'btn btn-primary'