config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'dashboards/index'

  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'dashboards#index'

  resources :admins, :users, :dashboards, :categories, :addresses
  resources :order_details, :wish_lists, :payment_gateways, :coupons, :payments
  resources :abouts, only: [:index]

    resources :cart_items do
      member do
        post 'add_product'
      end
      collection do
        get 'clear_cart'
      end
    end

    resources :user_orders do
      collection do
        get 'confirm_order'
        get 'add_order_address'
        get 'apply_discount'
      end
    end

    resources :products do
      collection do
        get 'search_product'
      end
    end

end

app/models/about.rb
class About < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

app/models/address.rb
class Address < ActiveRecord::Base
  
  # Association
  belongs_to :user
  has_many :user_orders
  # Validations
  validates_presence_of :address_1, :city, :state, :country, :zipcode
  validates :city, length: { minimum: 3}, format: { with: /[a-zA-Z]+/ }
  validates :state, length: { minimum: 3}, format: { with: /[a-zA-Z]+/ }
  validates :country, length: { minimum: 3}, format: { with: /[a-zA-Z]+/ }
  validates :zipcode,length: { is: 6}, format: { with: /[0-9]+/ }

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attribute_value.rb
class AttributeValue < ActiveRecord::Base

  # Associations
  has_many :product_attribute_associations, dependent: :destroy
  has_many :products, through: :product_attribute_associations
  has_many :product_attributes, through: :product_attribute_associations
  belongs_to :product_attribute

  # Validations
  validates_presence_of :value, :status

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  
  # Associations
  belongs_to :user
  belongs_to :product
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # Associations
  has_many :subcategories, dependent: :destroy, class_name: "Category", foreign_key: "category_id"
  belongs_to :category, class_name: "Category"
  has_and_belongs_to_many :products

  # Validations
  validates_presence_of :name
  validates :name, length: { in: 2..30}

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  has_many :user_orders
  has_many :used_coupons
  has_many :users, through: :used_coupons
end

app/models/image.rb
class Image < ActiveRecord::Base
  
  mount_uploader :avatar, AvatarUploader
  
  # Associaton
  belongs_to :product

  # Validations
  validates_presence_of :name, :main
  validates :name, length: { in: 3..30}

end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
  belongs_to :user_order
  belongs_to :product
end

app/models/payment_gateway.rb
class PaymentGateway < ActiveRecord::Base
  belongs_to :user_order

   attr_accessor :stripe_card_token

  # def save_with_payment
  #   if valid?
  #     customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
  #     self.stripe_customer_token = customer.id
  #     save!
  #   end
  #   rescue Stripe::InvalidRequestError => e
  #   logger.error "Stripe error while creating customer: #{e.message}"
  #   errors.add :base, "There was a problem with your credit card."
  #   false
  # end
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  # Assosiations
  has_many :cart_items
  has_many :order_details
  has_many :users, through: :cart_items
  has_many :images, dependent: :destroy
  has_many :product_attribute_associations, dependent: :destroy
  has_many :product_attributes, through: :product_attribute_associations
  has_many :attribute_values, through: :product_attribute_associations
  has_many :wish_lists
  has_and_belongs_to_many :categories

  # Validations
  validates_presence_of :name, :description, :price
  validates :name, length: { in: 3..30}
  validates :description, length: { in: 10..255}
  validates :price, format: { with: /\d+(\.\d{1,2})?/}
  
  # Scopes
  scope :category_products, ->(category_id) { joins(:categories).where('categories.category_id = ?', category_id) }

end

app/models/used_coupon.rb
class UsedCoupon < ActiveRecord::Base
  belongs_to :user
  belongs_to :coupon
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  # devise :omniauthable, :omniauth_providers => [:facebook]
  # devise :omniauthable, :omniauth_providers => [:google_oauth2]

  # Associations
  has_many :addresses, dependent: :destroy
  has_many :cart_items
  has_many :products, through: :cart_items
  has_many :user_orders, dependent: :destroy
  has_many :wish_lists
  has_many :used_coupons
  has_many :coupons, through: :used_coupons

  # Callbacks
  after_create :welcome_user

  # validates_presence_of :fname
  # validates :fname, length: { minimum: 3, too_short: "should be atleast 3 characters long."}, format: { with: /[a-zA-Z]+/ }
  # validates :phone, length: { minimum: 10, too_short: "should be atleast 10 digits long."}, format: { with: /\A[7-9]{1}[0-9]+/ }

  def self.from_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_initialize# do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.fname = auth.info.name   # user model has a fname
      # image = auth.info.image # assuming the user model has an image
    # end
    user.save
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # def facebook_profile_image(size)
  #   "http://graph.facebook.com/#{self.uid}/picture?type=#{size}"
  # end

  private
    def welcome_user
      NotificationMailer.delay(run_at: 3.minutes.from_now).welcome_email(self)
    end
end

app/models/user_order.rb
class UserOrder < ActiveRecord::Base
  belongs_to :billing_address, class_name: 'Address', foreign_key: 'billing_address_id'
  belongs_to :shipping_address, class_name: 'Address', foreign_key: 'shipping_address_id'
  has_many :order_details, dependent: :destroy
  has_one :payment_gateway
  belongs_to :user
  belongs_to :coupon
end

app/models/wish_list.rb
class WishList < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :check_product_in_cart, only: [:add_product]
  before_action :set_cart_items, only: [:index]
  # Actions
  def index
  end

  def show
  end

  def add_product
    if @cart_item.save
        flash[:notice] = "Product added successfully!"
      else
        flash[:alert] = "Something Went wrong!"
      end
      @cart_products = current_user.cart_items.joins(:product).select('products.id, products.name, cart_items.quantity, cart_items.quantity * products.price as amount, products.price')
      @total_amount = @cart_products.map(&:amount).sum
    end
  end

  def destroy
    @item = CartItem.find_by(product_id: params[:id])
    if @item.destroy
      flash[:notice] = "Product removed sucessfully!"
    else
      flash[:alert] = "Something went wrong, Try again!"
    end
    redirect_to cart_items_path
  end

  def clear_cart
    current_user.cart_items.destroy_all
    redirect_to payment_gateways_path
  end

  private
    def check_product_in_cart
      if user_signed_in?
      @cart_item = CartItem.find_by(product_id: params[:id])
      if @cart_item.present?
        @cart_item.quantity += 1
      else
        @cart_item = CartItem.new(product_id: params[:id], user_id: current_user.id, quantity: 1)
      end
    else
      respond_to do |format|
        format.js
      end
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_items/add_product.js.erb
<% if user_signed_in? %>
    $('#cart-total').text(" <%= item_counts %> item(s) - Rs. <%= @total_amount %>");
    $('#cart-list').html("<%= escape_javascript(render 'layouts/cart_product_list') %>");
<% else %>
    console.log("Else")
    $(".alert").html("You need to sign in first.");
<% end %>

app/views/cart_items/index.html.haml
.row
  .col-sm-12#content
    %h1 Shopping Cart
    - if @cart_products.present?
      .table-responsive
        %table.table.table-bordered
          %thead
            %tr
              %td.text-center Image
              %td.text-left Product Name
              %td.text-left Quantity
              %td.text-right Unit Price
              %td.text-right Total
          %tbody
          -@cart_products.each do |product|
            %tr
              %td.text-center
                = link_to image_tag("logo.png", height: 100, width: 200), product_path(product)
              %td.text-left
                = link_to product.name, product_path(product)
              %td.text-left
                .input-group.btn-block{:style => "max-width: 130px;"}
                  %input.form-control{id: "#{product.id}", size: "1", type: "text", value: "#{product.quantity}"}
                    %span.input-group-btn
                      = link_to '', cart_item_path(product), method: :delete, data: { confirm: 'Are You Sure?'}, type: "button", class: 'btn btn-danger fa fa-times-circle'
              %td.text-right
                = product.price
              %td.text-right
                = product.amount
      .row
        .col-sm-4.col-sm-offset-8
          %table.table.table-bordered
            %tbody
              %tr
                %td.text-left
                  %strong Sub-Total:
                %td.text-right
                  = @total_amount
              %tr
                %td.text-left
                  %strong Discount
                %td.text-right 0.0
              %tr
                %td.text-left
                  %strong Total:
                %td.text-right
                  = @total_amount
      .buttons
        .pull-left
          = link_to 'Continue Shopping', '/', type: 'button', class: 'btn btn-default'
        .pull-right
          = link_to 'Place Order', confirm_order_user_orders_path, type: 'button', class: 'btn btn-primary'
    - else
      %p There is no product in your cart.
      .buttons
        .pull-right
          = link_to 'Continue Shopping', '/', input_class: 'btn btn-primary'

      