config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'dashboards/index'

  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'dashboards#index'

  resources :admins, :users, :dashboards, :categories, :addresses
  resources :order_details, :wish_lists, :payment_gateways, :coupons, :payments
  resources :abouts, only: [:index]

    resources :cart_items do
      member do
        post 'add_product'
      end
      collection do
        get 'clear_cart'
      end
    end

    resources :user_orders do
      collection do
        get 'confirm_order'
        get 'add_order_address'
        get 'apply_discount'
      end
    end

    resources :products do
      collection do
        get 'search_product'
      end
    end

end

app/models/about.rb
class About < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

app/models/address.rb
class Address < ActiveRecord::Base
  
  # Association
  belongs_to :user
  has_many :user_orders
  # Validations
  validates_presence_of :address_1, :city, :state, :country, :zipcode
  validates :city, length: { minimum: 3}, format: { with: /[a-zA-Z]+/ }
  validates :state, length: { minimum: 3}, format: { with: /[a-zA-Z]+/ }
  validates :country, length: { minimum: 3}, format: { with: /[a-zA-Z]+/ }
  validates :zipcode,length: { is: 6}, format: { with: /[0-9]+/ }

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attribute_value.rb
class AttributeValue < ActiveRecord::Base

  # Associations
  has_many :product_attribute_associations, dependent: :destroy
  has_many :products, through: :product_attribute_associations
  has_many :product_attributes, through: :product_attribute_associations
  belongs_to :product_attribute

  # Validations
  validates_presence_of :value, :status

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  
  # Associations
  belongs_to :user
  belongs_to :product
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # Associations
  has_many :subcategories, dependent: :destroy, class_name: "Category", foreign_key: "category_id"
  belongs_to :category, class_name: "Category"
  has_and_belongs_to_many :products

  # Validations
  validates_presence_of :name
  validates :name, length: { in: 2..30}

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  has_many :user_orders
  has_many :used_coupons
  has_many :users, through: :used_coupons
end

app/models/image.rb
class Image < ActiveRecord::Base
  
  mount_uploader :avatar, AvatarUploader
  
  # Associaton
  belongs_to :product

  # Validations
  validates_presence_of :name, :main
  validates :name, length: { in: 3..30}

end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
  belongs_to :user_order
  belongs_to :product
end

app/models/payment_gateway.rb
class PaymentGateway < ActiveRecord::Base
  belongs_to :user_order

   attr_accessor :stripe_card_token

  # def save_with_payment
  #   if valid?
  #     customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
  #     self.stripe_customer_token = customer.id
  #     save!
  #   end
  #   rescue Stripe::InvalidRequestError => e
  #   logger.error "Stripe error while creating customer: #{e.message}"
  #   errors.add :base, "There was a problem with your credit card."
  #   false
  # end
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  # Assosiations
  has_many :cart_items
  has_many :order_details
  has_many :users, through: :cart_items
  has_many :images, dependent: :destroy
  has_many :product_attribute_associations, dependent: :destroy
  has_many :product_attributes, through: :product_attribute_associations
  has_many :attribute_values, through: :product_attribute_associations
  has_many :wish_lists
  has_and_belongs_to_many :categories

  # Validations
  validates_presence_of :name, :description, :price
  validates :name, length: { in: 3..30}
  validates :description, length: { in: 10..255}
  validates :price, format: { with: /\d+(\.\d{1,2})?/}
  
  # Scopes
  scope :category_products, ->(category_id) { joins(:categories).where('categories.category_id = ?', category_id) }

end

app/models/used_coupon.rb
class UsedCoupon < ActiveRecord::Base
  belongs_to :user
  belongs_to :coupon
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  # devise :omniauthable, :omniauth_providers => [:facebook]
  # devise :omniauthable, :omniauth_providers => [:google_oauth2]

  # Associations
  has_many :addresses, dependent: :destroy
  has_many :cart_items
  has_many :products, through: :cart_items
  has_many :user_orders, dependent: :destroy
  has_many :wish_lists
  has_many :used_coupons
  has_many :coupons, through: :used_coupons

  # Callbacks
  after_create :welcome_user

  # validates_presence_of :fname
  # validates :fname, length: { minimum: 3, too_short: "should be atleast 3 characters long."}, format: { with: /[a-zA-Z]+/ }
  # validates :phone, length: { minimum: 10, too_short: "should be atleast 10 digits long."}, format: { with: /\A[7-9]{1}[0-9]+/ }

  def self.from_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_initialize# do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.fname = auth.info.name   # user model has a fname
      # image = auth.info.image # assuming the user model has an image
    # end
    user.save
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # def facebook_profile_image(size)
  #   "http://graph.facebook.com/#{self.uid}/picture?type=#{size}"
  # end

  private
    def welcome_user
      NotificationMailer.delay(run_at: 3.minutes.from_now).welcome_email(self)
    end
end

app/models/user_order.rb
class UserOrder < ActiveRecord::Base
  belongs_to :billing_address, class_name: 'Address', foreign_key: 'billing_address_id'
  belongs_to :shipping_address, class_name: 'Address', foreign_key: 'shipping_address_id'
  has_many :order_details, dependent: :destroy
  has_one :payment_gateway
  belongs_to :user
  belongs_to :coupon
end

app/models/wish_list.rb
class WishList < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # Filters
  before_action :set_product, only: [:show]

  # Actions
  def show
  end

  def search_product
    unless params[:search] == ""
      @products = Product.where('name LIKE ?', params[:search]).paginate(page: params[:page], per_page: 8)
      unless @products.present?
        flash[:alert] = "#{params[:search]} is not available this time."
      end
      render 'dashboards/index'
    else
      flash[:alert] = "Enter Product name and Try again!"
      redirect_to root_path
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/show.html.haml
.row
  .col-sm-12#content
    .row
      .col-sm-8
        %ul.thumbnails
          -@product.images.each do |img|
            -if img.main
              %li
                .thumbnail
                  = link_to image_tag("#{img.avatar.url}", height: 100, width: 200), product_path(@product)
            -if img.main
              %li.image-additional
                .thumbnail
                  = link_to image_tag("#{img.avatar.url}"), product_path(@product)
        %ul.nav.nav-tabs
          %li.active
            %a{"data-toggle" => "tab", :href => "#tab-description"} Description
          %li
            %a{"data-toggle" => "tab", :href => "#tab-secification"} Specification
        .tab-content
          .tab-pane.active#tab-description
            %div
              %p
                %b 
                  = @product.description
          .tab-pane#tab-secification
            %div
              %table.table.table-bordered
                %thead
                  %tr
                    %td
                      %b Attribute
                    %td
                      %b Value
                - @product.product_attributes.each do |attribute|
                  %tbody
                    %tr
                      %td
                        %b
                          = attribute.name
                      - attribute.attribute_values.each do |attribute_value|
                        %td
                          = attribute_value.value
      .col-sm-4
        .btn-group
          %button.btn.btn-default
            = link_to '', wish_lists_path(@product), remote: true, method: :post, class: "fa fa-heart"
        %h1 
          = @product.name
        %table.table
          %tbody#wishlist-row
            %tr
              %td Product Code
              %td.text-right
                %b
                  = @product.id
            %tr
              %td Availability
              -if @product.status
                %td.text-right
                  %b.true
                    In Stock
              -else
                %td.text-right
                  %b.false
                    Out of Stock
            %tr
              %td Price
              %td.text-right
                %h3
                  = @product.price
        #product
          .form-group
            %br
            #button-cart
              = link_to 'ADD TO CART', add_product_cart_item_path(@product), remote: true, method: :post, class: 'btn btn-primary btn-lg btn-block'
      